-- MySQL Script generated by MySQL Workbench
-- Tue 03 Mar 2020 18:24:38 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP DATABASE IF EXISTS `mydb`;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Weight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Weight` (
  `id` INT NOT NULL,
  `value` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Date` (
  `timestamp` INT NOT NULL,
  `price` DOUBLE NULL,
  `date_return` DOUBLE NULL,
  `date_update` BOOLEAN NULL,
  PRIMARY KEY (`timestamp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Security`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Security` (
  `price` DOUBLE NOT NULL,
  `security_return` DOUBLE NULL,
  `fk_weight` INT NOT NULL,
  `fk_date` INT NOT NULL,
  INDEX `fk_weight_idx` (`fk_weight` ASC),
  INDEX `fk_date_idx` (`fk_date` ASC),
  PRIMARY KEY (`fk_weight`, `fk_date`),
  CONSTRAINT `fk_weight`
    FOREIGN KEY (`fk_weight`)
    REFERENCES `mydb`.`Weight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_date`
    FOREIGN KEY (`fk_date`)
    REFERENCES `mydb`.`Date` (`timestamp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
